name: Checks
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    name: analyse
    uses: ./.github/workflows/setup.yml
    with:
      command: composer check
