name: Checks
on:
  push:
    branches:
      - beta
      - main
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  analyse:
    name: analyse
    uses: ./.github/workflows/setup-api.yml
    with:
      command: composer check
