name: Setup

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, xdebug
          coverage: xdebug

      - name: cache composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: install composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: cache npm dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: install npm dependencies
        run: npm ci

      - name: build frontend
        run: npm run build

      - name: prepare environment
        run: |
          cp ${{ github.workspace }}/.env.example .env
          php artisan key:generate

      - name: run command
        run: ${{ inputs.command }}
